services:
  - type: web
    name: personality-test-app
    env: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app --workers=1 --threads=1 --timeout=300 --bind=0.0.0.0:$PORT

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.10